version: '3.8'
services:
  spark-master:
    container_name: spark-master
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: "2g"
    build:
      context: ./Spark
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
      - "18080:18080"
    networks:
      - spark-net
    command: sh spark-master.sh

  spark-worker:
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: "2g"
    build:
      context: ./Spark
    depends_on:
      - spark-master
    ports:
      - "8081-8089:8081"
    networks:
      - spark-net
    command: sh spark-worker.sh

  spark-client:
    container_name: spark-client
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: "2g"
    build:
      context: ./spark-client
    ports:
      - "8888:8888"
      - "4041:4040"
    networks:
      - spark-net
    volumes:
      - ./spark_client/examples:/opt/examples

# S3 compatible object storage: MinIO
  minio:
    container_name: minio
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: "2g"
    image: "minio/minio:RELEASE.2023-05-04T21-44-30Z"
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - spark-net
    environment:
      MINIO_ACCESS_KEY: "telcoaz"
      MINIO_SECRET_KEY: "Telco12345"
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
   minio:
      driver: local

networks:
  spark-net:
    external: true


  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-logs
    networks:
      - spark-net

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.1
    container_name: schema-registry
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    ports:
      - "8081:8081"
    networks:
      - spark-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - spark-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
